### ISSUE TITLE
Eject Method plain has changed to bare

### ISSUE THREAD

**Issue by juliosouza-pushstart** [bitrise-steplib/steps-expo-detach#7] opened 2019-09-18 16:43 UTC
As described in https://github.com/expo/expo-cli/pull/805, the eject-method `plain` is now called `bare`. I'm not sure if there are side effects to that change though.

Trying to run the step as it is, without providing expo username will trigger an error due to that change.

**Comment by bitce** [comment] 2019-09-19 13:54
Thanks for pointing this out @juliosouza-pushstart! We've notified the team and we'll make the necessary changes :)

**Comment by superphil0** [comment] 2019-10-07 13:57
is this already updated? It asked me for expo name now and failed at eject because it wants to eject to expokit,

regardless I would rather have the possibilty for an already ejected project to be built (ios and android folders checked in in git, do I have to write my own build script or you support this out of the box? :)

**Comment by bitce** [comment] 2019-10-16 11:28
Hi @superphil0! 

This change was just recently implemented in: https://github.com/bitrise-steplib/steps-expo-detach/pull/8

That should require neither, I believe you can simply skip the detach step for already ejected projects :)

**Comment by superphil0** [comment] 2019-10-24 08:20
so i create the app anew he autodetected expo and i removed the eject step, the problem is that there is no kind of bundling step in here, this is missing, this is also the "side effect" @juliosouza-pushstart is talking about

**Comment by bitce** [comment] 2019-11-05 10:28
Hi @superphil0! I do not entirely follow, unfortunately, can you by any chance send us a build URL of the problem you're facing we can check it out? 🙂

**Comment by superphil0** [comment] 2019-12-05 10:17
Hey @bitce  I managed now to build my app, I am in bare and what I didnt understand before is that when you build with bare it has nothing to do with expo anymore, but is just regular react native build

**Comment by Roland-Bak** [comment] 2019-12-05 11:39
Thanks for the update, @superphil0!

Can you by any chance send us a build URL in order for us to see how this could be improved? :)

**Comment by superphil0** [comment] 2019-12-21 11:03
https://app.bitrise.io/build/bc2437543b41eff3

**Comment by barinali** [comment] 2020-10-14 22:17
It seems `--eject-method` is removed out of `expo-cli`. The step needs to be revised accordingly. Right now, my workflows including a `[Beta] Expo Eject` step are failing.

![image](https://user-images.githubusercontent.com/1263419/96051412-bf689300-0e7b-11eb-9659-60a1aba79633.png)


One may apply the suggestion from https://github.com/bitrise-steplib/steps-expo-detach/issues/7#issuecomment-709657674 or they may incorporate `expo eject` manually by adding a "script" step and running the following in it;

```sh
npm install -g expo-cli

expo eject --non-interactive
```

**Comment by jeremyalan** [comment] 2020-10-16 00:24
@barinali It looks like this is a brand new issue (new release pushed to NPM yesterday).  The quick fix is to explicitly set the `expo-cli` version to 3.27.14 in your Bitrise workflow.

**Comment by adborbas** [comment] 2021-01-07 12:02
Thanks for reporting the issue, this should now be fixed with the [1.0.0](https://github.com/bitrise-steplib/steps-expo-detach/releases/tag/1.0.0) release. Please feel free to open a new issue in case the problem still occurs or you have any other issue.

**Closed as completed by adborbas** 2021-01-07 12:02 UTC
